version: '3'
services:
  # api:
  #   container_name: saintp_api
  #   image: saintp_api
  #   restart: always
  #   ports:
  #     - '5000:81'
  #   networks:
  #     nwk1:
  #       ipv4_address: 10.1.0.4
  db:
    container_name: saintp_postgres
    image: saintp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
      PGDATA: /var/lib/postgresql/data/pgdata 
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d
      - ./postgres/data/:/var/lib/postgresql/data
    networks:
      nwk1:
        ipv4_address: 10.1.0.2
  
networks:
  nwk1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1